import './globals.scss';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import TranslateProvider from '@/components/TranslateProvider/TranslateProvider';
import initTranslations from '../i18n';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, ['default']);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TranslateProvider
          locale={locale}
          resources={resources}
          namespaces={['default']}
        >
          <Header />
          {children}
          <Footer />
        </TranslateProvider>
      </body>
    </html>
  );
}
